
import { Question, Dimension } from './types';

export const QUESTIONS: Question[] = [
  // MIND: Extraversion (E) vs. Introversion (I)
  { id: 1, text: "You regularly make new friends.", dimension: Dimension.EI, reverse: false },
  { id: 2, text: "You spend a lot of your free time exploring various random topics that pique your interest.", dimension: Dimension.EI, reverse: false },
  { id: 3, text: "At social events, you rarely try to introduce yourself to new people and mostly talk to the ones you already know.", dimension: Dimension.EI, reverse: true },
  { id: 4, text: "You feel energized after spending time with a large group of people.", dimension: Dimension.EI, reverse: false },
  { id: 5, text: "You prefer a small gathering of close friends over a large party.", dimension: Dimension.EI, reverse: true },
  { id: 6, text: "You enjoy being the center of attention.", dimension: Dimension.EI, reverse: false },
  { id: 7, text: "You find it easy to strike up a conversation with strangers.", dimension: Dimension.EI, reverse: false },
  { id: 8, text: "You feel drained if you have to socialize for too long.", dimension: Dimension.EI, reverse: true },
  { id: 9, text: "You prefer to express your thoughts in writing rather than speaking.", dimension: Dimension.EI, reverse: true },
  { id: 10, text: "You are often the first to react in a social situation.", dimension: Dimension.EI, reverse: false },
  { id: 11, text: "You usually wait for others to approach you in social settings.", dimension: Dimension.EI, reverse: true },
  { id: 12, text: "Your energy levels increase when you are around active people.", dimension: Dimension.EI, reverse: false },
  { id: 13, text: "You need significant alone time to recharge after a busy day.", dimension: Dimension.EI, reverse: true },
  { id: 14, text: "You are naturally quiet and reserved.", dimension: Dimension.EI, reverse: true },
  { id: 15, text: "You find it easy to share your feelings with others.", dimension: Dimension.EI, reverse: false },

  // ENERGY: Sensing (S) vs. iNtuition (N)
  { id: 16, text: "You often spend time exploring unrealistic yet intriguing ideas.", dimension: Dimension.SN, reverse: true },
  { id: 17, text: "Your travel plans are usually well thought out.", dimension: Dimension.SN, reverse: false },
  { id: 18, text: "You are more of a detail-oriented than a big-picture person.", dimension: Dimension.SN, reverse: false },
  { id: 19, text: "You often get as lost in thoughts that you ignore or forget your surroundings.", dimension: Dimension.SN, reverse: true },
  { id: 20, text: "You prefer to rely on your experience rather than your imagination.", dimension: Dimension.SN, reverse: false },
  { id: 21, text: "You are fascinated by complex, abstract theories.", dimension: Dimension.SN, reverse: true },
  { id: 22, text: "You prefer to follow a well-trodden path than to strike out on your own.", dimension: Dimension.SN, reverse: false },
  { id: 23, text: "You often wonder how things could be different than they are.", dimension: Dimension.SN, reverse: true },
  { id: 24, text: "You focus on the 'here and now' rather than the 'what if'.", dimension: Dimension.SN, reverse: false },
  { id: 25, text: "You value practicality more than creative flair.", dimension: Dimension.SN, reverse: false },
  { id: 26, text: "You frequently find yourself looking for deeper meanings in things.", dimension: Dimension.SN, reverse: true },
  { id: 27, text: "You are very observant of your physical environment.", dimension: Dimension.SN, reverse: false },
  { id: 28, text: "You are more interested in what is possible than what is real.", dimension: Dimension.SN, reverse: true },
  { id: 29, text: "You like to have a clear, step-by-step procedure for tasks.", dimension: Dimension.SN, reverse: false },
  { id: 30, text: "You often have 'hunches' about things that turn out to be true.", dimension: Dimension.SN, reverse: true },

  // NATURE: Thinking (T) vs. Feeling (F)
  { id: 31, text: "You find it easy to stay relaxed even when there is some pressure.", dimension: Dimension.TF, reverse: false },
  { id: 32, text: "You rarely worry about how your actions affect other people.", dimension: Dimension.TF, reverse: false },
  { id: 33, text: "Your emotions control you more than you control them.", dimension: Dimension.TF, reverse: true },
  { id: 34, text: "You value logic more than feelings when making important decisions.", dimension: Dimension.TF, reverse: false },
  { id: 35, text: "You are very sentimental.", dimension: Dimension.TF, reverse: true },
  { id: 36, text: "In a disagreement, the truth should be more important than people's feelings.", dimension: Dimension.TF, reverse: false },
  { id: 37, text: "You are moved by others' emotions and stories.", dimension: Dimension.TF, reverse: true },
  { id: 38, text: "You are generally more analytical than empathetic.", dimension: Dimension.TF, reverse: false },
  { id: 39, text: "You find it hard to say no to people.", dimension: Dimension.TF, reverse: true },
  { id: 40, text: "You believe that being objective is better than being subjective.", dimension: Dimension.TF, reverse: false },
  { id: 41, text: "You often take things personally.", dimension: Dimension.TF, reverse: true },
  { id: 42, text: "You are more interested in why people feel the way they do than what they think.", dimension: Dimension.TF, reverse: true },
  { id: 43, text: "You prefer to be right even if it makes you unpopular.", dimension: Dimension.TF, reverse: false },
  { id: 44, text: "You try to maintain harmony in your social circle at all costs.", dimension: Dimension.TF, reverse: true },
  { id: 45, text: "You make decisions based on what your gut tells you is right for everyone.", dimension: Dimension.TF, reverse: true },

  // TACTICS: Judging (J) vs. Perceiving (P)
  { id: 46, text: "You complete your chores before allowing yourself to relax.", dimension: Dimension.JP, reverse: false },
  { id: 47, text: "You enjoy having a wide range of options, even if it makes decision-making harder.", dimension: Dimension.JP, reverse: true },
  { id: 48, text: "Your work style is closer to spontaneous bursts of energy than organized and consistent efforts.", dimension: Dimension.JP, reverse: true },
  { id: 49, text: "You find it easy to stick to a routine.", dimension: Dimension.JP, reverse: false },
  { id: 50, text: "You like to have a 'to-do' list for each day.", dimension: Dimension.JP, reverse: false },
  { id: 51, text: "You often end up doing things at the last minute.", dimension: Dimension.JP, reverse: true },
  { id: 52, text: "You feel uncomfortable if you don't have a plan for your day.", dimension: Dimension.JP, reverse: false },
  { id: 53, text: "You are a very punctual person.", dimension: Dimension.JP, reverse: false },
  { id: 54, text: "You enjoy improvising when you find yourself in a new situation.", dimension: Dimension.JP, reverse: true },
  { id: 55, text: "You prefer to finish one project before starting another.", dimension: Dimension.JP, reverse: false },
  { id: 56, text: "You are easily distracted by new and exciting opportunities.", dimension: Dimension.JP, reverse: true },
  { id: 57, text: "You find it easy to stay organized.", dimension: Dimension.JP, reverse: false },
  { id: 58, text: "You like to leave your options open as long as possible.", dimension: Dimension.JP, reverse: true },
  { id: 59, text: "You often make a plan and stick to it.", dimension: Dimension.JP, reverse: false },
  { id: 60, text: "You are often described as a flexible, 'go with the flow' person.", dimension: Dimension.JP, reverse: true },
];
